name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  GHCR_IMAGE_NAME: "ghcr.io/pikhovkin/${GITHUB_REPOSITORY:10}"
  IMAGE_NAME: "pikhovkin/${GITHUB_REPOSITORY:10}"
  TAG: ${GITHUB_REF:10}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: |
          docker build -f docker/Dockerfile -t ${{ env.GHCR_IMAGE_NAME }}:test .
      - name: Docker push
        run: |
          docker push ${{ env.GHCR_IMAGE_NAME }}:test
